-- Services shown on the public website (managed under Administration → Website services).
CREATE TABLE IF NOT EXISTS site_services (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(80) NOT NULL,
    title VARCHAR(120) NOT NULL,
    category ENUM('digital', 'hosting') NOT NULL DEFAULT 'digital',
    icon VARCHAR(40) NOT NULL DEFAULT 'stars',
    summary VARCHAR(300) NOT NULL,
    description TEXT NULL,
    features TEXT NULL,
    price_from BIGINT UNSIGNED NULL,
    price_note VARCHAR(80) NULL,
    status ENUM('active', 'hidden') NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_site_services_slug (slug),
    INDEX idx_site_services_list (status, category, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO site_services (slug, title, category, icon, summary, description, features, sort_order, created_at, updated_at) VALUES
('website-design', 'Website designing', 'digital', 'window-stack',
 'Modern, mobile-friendly websites that look great, load fast and turn visitors into customers.',
 'Your website is often the first thing people see about your business. We design and build websites that match your brand, work perfectly on phones, and make it easy for visitors to call you, message you or buy from you.\n\nFrom a simple business website to a full corporate site, we take care of design, content structure, development and launch — and we can host and maintain it for you afterwards.',
 'Custom design that matches your brand\nMobile-friendly and fast loading\nContact forms, WhatsApp and call buttons\nBasic on-page SEO set up\nEasy-to-update pages (WordPress or custom)\nLaunch on your own domain with SSL',
 10, NOW(), NOW()),
('app-development', 'App designing & development', 'digital', 'phone',
 'Android and iOS apps and web apps, designed around your users and built to grow with your business.',
 'Whether you need an app for your customers, your staff or a new product idea, we help you plan it, design the screens and build it properly.\n\nWe start with what the app must do for your users, create clickable designs you can review, and then develop, test and publish the app — with support after launch.',
 'Android and iOS apps\nWeb apps and customer portals\nUI/UX design and clickable prototypes\nAdmin panel to manage your content\nPlay Store and App Store publishing\nSupport and updates after launch',
 20, NOW(), NOW()),
('digital-marketing', 'Digital marketing', 'digital', 'graph-up-arrow',
 'Reach the right people online with planned campaigns on Google, Facebook, Instagram and more.',
 'Good marketing brings the right people to your business at the right time. We plan campaigns around your goals — more calls, more enquiries or more sales — and run them across search and social media.\n\nYou get clear reports on what is working, and we keep improving the campaigns month by month.',
 'Google Ads and search campaigns\nFacebook and Instagram ads\nLead generation campaigns\nLanding pages for your ads\nConversion tracking set up\nMonthly performance reports',
 30, NOW(), NOW()),
('seo', 'Search engine optimisation (SEO)', 'digital', 'search',
 'Help customers find you on Google with technical fixes, better content and local SEO.',
 'SEO helps your business show up when people search for what you offer. We look at your website, fix what holds it back, improve your content and set up your Google Business Profile for local searches.\n\nSEO takes time to show results, so we work in clear monthly steps and report progress honestly.',
 'Website SEO audit\nKeyword research\nOn-page and technical SEO\nGoogle Business Profile (local SEO)\nContent suggestions\nMonthly progress reports',
 40, NOW(), NOW()),
('social-media', 'Social media management', 'digital', 'megaphone',
 'Consistent, on-brand posts and a content calendar that keeps your audience engaged.',
 'Staying active on social media takes time. We plan a content calendar, design posts and reels, write captions and publish them regularly on your pages, so your brand stays visible and consistent.',
 'Content calendar every month\nPost and reel designs\nCaptions and hashtags\nFacebook, Instagram and LinkedIn\nPage set-up and optimisation\nMonthly insights report',
 50, NOW(), NOW()),
('branding', 'Graphic design & branding', 'digital', 'palette',
 'Logos, brand identity and marketing designs that make your business look professional everywhere.',
 'A strong brand makes people remember and trust you. We design logos and brand guidelines, and all the everyday material your business needs — online and in print.',
 'Logo design\nBrand colours and fonts\nBusiness cards and letterheads\nBrochures, flyers and banners\nSocial media creatives\nPrint-ready and web files',
 60, NOW(), NOW()),
('ecommerce', 'E-commerce websites', 'digital', 'cart3',
 'Online stores with products, payments and orders — ready to start selling.',
 'Sell your products online with a store that is easy for customers to use and easy for you to manage. We set up your catalogue, payments, shipping options and order notifications.',
 'Product catalogue and categories\nOnline payments (UPI, cards, net banking)\nShipping and delivery options\nOrder and stock management\nDiscount coupons\nMobile-friendly checkout',
 70, NOW(), NOW()),
('web-hosting', 'Web hosting', 'hosting', 'hdd-network',
 'Fast, secure hosting for WordPress, PHP and static sites, managed from a simple control panel.',
 'Host your websites on fast servers with everything included: files, FTP, databases and SSL. You manage it all from your own client area, and our team is there when you need help.',
 'Websites, files and FTP\nMySQL databases\nSSL certificates\nEasy control panel\nOnline invoices and payments\nHelp from our team',
 110, NOW(), NOW()),
('domains', 'Domains & DNS', 'hosting', 'globe2',
 'Register or connect your domain and manage every DNS record from one clear editor.',
 'Get the right domain name for your business and manage it in one place. Our DNS editor makes it simple to point your domain to your website, email and other services.',
 'Domain registration and renewal\nConnect domains you already own\nFull DNS editor\nReminders before renewal',
 120, NOW(), NOW()),
('business-email', 'Business email', 'hosting', 'envelope-paper',
 'Professional addresses like you@yourbrand.com, with webmail you can open from anywhere.',
 'Look professional with email on your own domain. Create mailboxes for your team, set up aliases and forwarding, and read mail in the browser or on your phone.',
 'Email on your own domain\nMailboxes for your team\nAliases and forwarding\nWebmail from any browser\nWorks with Outlook, Gmail and phones',
 130, NOW(), NOW());
