<?php
declare(strict_types=1);

namespace App\Support;

use App\Core\Migrator;
use PDO;
use RuntimeException;

final class Installer
{
    public const LOCK = BASE_PATH . '/storage/installed.lock';
    public const CONFIG = BASE_PATH . '/config/config.php';

    public static function isInstalled(): bool
    {
        return is_file(self::LOCK);
    }

    /**
     * @param array $in app_url, db_host, db_port, db_name, db_user, db_pass, admin_name, admin_email, admin_password, company
     */
    public static function install(array $in): void
    {
        if (self::isInstalled()) {
            throw new RuntimeException('Already installed.');
        }
        $db = [
            'host' => $in['db_host'],
            'port' => (int) $in['db_port'],
            'name' => $in['db_name'],
            'user' => $in['db_user'],
            'pass' => $in['db_pass'],
        ];
        $pdo = \App\Core\DB::connect($db);
        Migrator::run($pdo);

        $now = date('Y-m-d H:i:s');
        $superRole = (int) $pdo->query("SELECT id FROM roles WHERE is_super = 1 ORDER BY id LIMIT 1")->fetchColumn();
        $stmt = $pdo->prepare('SELECT COUNT(*) FROM users WHERE email = ?');
        $stmt->execute([strtolower($in['admin_email'])]);
        if ((int) $stmt->fetchColumn() === 0) {
            $pdo->prepare('INSERT INTO users (type, role_id, name, email, password_hash, status, password_changed_at, created_at, updated_at)
                           VALUES (\'admin\', ?, ?, ?, ?, \'active\', ?, ?, ?)')
                ->execute([$superRole, $in['admin_name'], strtolower($in['admin_email']), password_hash($in['admin_password'], PASSWORD_DEFAULT), $now, $now, $now]);
        }
        $settings = $pdo->prepare('INSERT INTO settings (`key`, `value`, updated_at) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)');
        if (!empty($in['company'])) {
            $settings->execute(['company.legal_name', $in['company'], $now]);
            $settings->execute(['site.name', $in['company'], $now]);
        }
        $settings->execute(['contact.email', strtolower($in['admin_email']), $now]);

        if (!is_file(self::CONFIG)) {
            $config = [
                'app' => [
                    'url' => rtrim($in['app_url'], '/'),
                    'key' => 'base64:' . base64_encode(random_bytes(32)),
                    'timezone' => 'Asia/Kolkata',
                    'debug' => false,
                    'trust_proxy' => false,
                ],
                'db' => $db,
            ];
            $php = "<?php\n// Generated by the WebEdge installer on $now\nreturn " . var_export($config, true) . ";\n";
            if (file_put_contents(self::CONFIG, $php, LOCK_EX) === false) {
                throw new RuntimeException('Could not write config/config.php. Check folder permissions.');
            }
            @chmod(self::CONFIG, 0640);
        }
        file_put_contents(self::LOCK, $now);
    }

    public static function requirements(): array
    {
        return [
            'PHP 8.1 or newer' => version_compare(PHP_VERSION, '8.1.0', '>='),
            'PDO MySQL extension' => extension_loaded('pdo_mysql'),
            'OpenSSL extension' => extension_loaded('openssl'),
            'mbstring extension' => extension_loaded('mbstring'),
            'cURL extension' => extension_loaded('curl'),
            'fileinfo extension' => extension_loaded('fileinfo'),
            'config/ is writable' => is_writable(BASE_PATH . '/config'),
            'storage/ is writable' => is_writable(BASE_PATH . '/storage'),
            'public/uploads/ is writable' => is_writable(BASE_PATH . '/public/uploads'),
        ];
    }
}
